### ISSUE TITLE
Another way to receive refresh token

### ISSUE THREAD

**Issue by Loukei** [chilarai/Qt-Google-OAuth#1]
Hello, I was working on Qt google OAuth2 too.
Here is my way to change the result form `QOAuth2AuthorizationCodeFlow::authorizeWithBrowser` signal.

The authorizeWithBrowser is emit form protected function `void QOAuth2AuthorizationCodeFlow::resourceOwnerAuthorization`,which is using `QUrl QOAuth2AuthorizationCodeFlow::buildAuthenticateUrl` to modify the result.

But we don't need to override buildAuthenticateUrl() function, in source code, this function use `d->modifyParametersFunction(Stage::RequestingAuthorization, &p);` to change the final result.

So my solution is simply set `QAbstractOAuth::ModifyParametersFunction`.
Here's my code snippet, m_google is `QOAuth2AuthorizationCodeFlow` object.

``` c++
m_google->setModifyParametersFunction(buildModifyParametersFunction());

QAbstractOAuth::ModifyParametersFunction GDriveService::buildModifyParametersFunction()
{
    const QUrl clientIdentifier = m_google->clientIdentifier();
    const QUrl clientIdentifierSharedKey = m_google->clientIdentifierSharedKey();
    return [clientIdentifier,clientIdentifierSharedKey]
            (QAbstractOAuth::Stage stage, QVariantMap *parameters){
        if(stage == QAbstractOAuth::Stage::RequestingAuthorization){
            /* setup Authoriation Url here */
            parameters->insert("access_type","offline"); /* Request refresh token*/
            parameters->insert("prompt","consent"); /* force user check scope again */
        }
        if(stage == QAbstractOAuth::Stage::RefreshingAccessToken){
            parameters->insert("client_id",clientIdentifier);
            parameters->insert("client_secret",clientIdentifierSharedKey);
        }
    };
}
```

The `QOAuth2AuthorizationCodeFlow::refreshAccessToken`  behavior is also changed.

PS: My Qt version is 5.13.2

## Reference
[QOAuth2AuthorizationCodeFlow::buildAuthenticateUrl source code](https://code.woboq.org/qt5/qtnetworkauth/src/oauth/qoauth2authorizationcodeflow.cpp.html#_ZN28QOAuth2AuthorizationCodeFlow20buildAuthenticateUrlERK4QMapI7QString8QVariantE)
[QAbstractOAuth::modifyParametersFunction() Doc](https://doc.qt.io/qt-5/qabstractoauth.html#modifyParametersFunction)

**Comment by chilarai** [comment]
Yes, you are right. We don't have to override `buildAuthenticateUrl()` to achieve the same.  But the objective of the code here is to just demonstrate the Google OAuth with Qt. So, it works. 

Feel free to commit any optimization code, if any

**Comment by Loukei** [comment]
I agree, it's not problem. I just provide another method to achieve that feature.
Thanks for reading.
